# Basic
title: Echo
subtitle: å°å¤©åœ°
description: welcome to Echo's world~
# å¤´åƒé‡Œé¢çš„æ ‡é¢˜
avatarTitle: Echochan
# å¤´åƒé‡Œé¢çš„æè¿°
avatarDesc: ç”Ÿæ´» / éšç¬”
url: "http://echochan.io"

# Comment
comment:
    # disqus: echo
    duoshuo: echo 

# Social
social:
    weibo: Echoå®¹ 
    github: echochan
    # twitter: 
    mail: crecho@live.cn




# ã€Š----------------- ä¸Šé¢çš„ä¿¡æ¯ä¿®æ”¹æˆä½ è‡ªå·±çš„ ---------------------------ã€‹
#
#
#  _post/ ä¸‹çš„æ–‡ç« æ›´æ¢æˆä½ è‡ªå·±çš„æ–‡ç« 
#  å¸®å¿™starä¸€ä¸‹ï¼Œæ„Ÿè°¢~ğŸ˜† åœ°å€ï¼š https://github.com/leopardpan/leopardpan.github.io
#
#
# ã€Š--------------- ä¸‹é¢çš„ä¿¡æ¯å¯ä»¥è‡ªè¡Œé€‰æ‹©æ˜¯å¦ä¿®æ”¹ ------------------------ã€‹


permalink: /:year/:month/:title/
# Format
highlighter: rouge

textColor: #A0522D

# supported colors: blue, green, purple, red, orange or slate. If you need clear, leave it empty.
cover_color: clear

# The blog button should not be removed.
blog_button:
    title: ä¸»é¡µ

# Navigation buttons in the front page.s
nav:
    - {title: æ•…äº‹, description: archive, url: '/archive'}   
    - {title: ç‚¹æ»´, description: tags, url: '/tags'}      
    - {title: æ‡‚æˆ‘, description: about, url: '/about'}      
    

# Pagination
gems: [jekyll-paginate,jekyll-sitemap]
paginate: 20
paginate_path: "page/:num/"


